mongodb:
  primary:
    host: ds147659.mlab.com
    port: 47659
    database: projetorest
    username: userpadrao
    password: 123456u
  secondary:
    host: ds151702.mlab.com
    port: 51702
    database: projetorest2
    username: userpadrao
    password: 123456u